import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import CycleButton from "./components/cycleButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const colors: string[] = [
  "red",
  "green",
  "blue",
  "yellow",
  "purple",
  "orange",
  "pink",
  "cyan",
  "magenta",
  "lime",
  "teal",
  "indigo",
  "violet",
  "fuchsia",
  "lightblue",
  "lightgreen",
  "lightred",
  "lightyellow",
  "lightpurple",
  "lightorange",
  "lightpink",
  "lightcyan",
  "lightmagenta",
  "lightlime",
  "lightteal",
  "lightindigo",
  "lightviolet",
  "lightfuchsia",
  "darkblue",
  "darkgreen",
  "darkred",
  "darkyellow",
  "darkpurple",
  "darkorange",
  "darkpink",
  "darkcyan",
  "darkmagenta",
  "darklime",
  "darkteal",
  "darkindigo",
  "darkviolet",
  "darkfuchsia",

  "white",
  "gray",
  "grey",
  "lightgray",
  "lightgrey",

  "transparent",
];
function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <Image
            className={styles.logo}
            src="/logo.svg"
            alt="Next.js logo"
            width={180}
            height={38}
            priority
          />

          <div className={styles.ctas}>
            <a
              className={styles.primary}
              target="_blank"
              rel="noopener noreferrer"
            >
              <Image
                className={styles.logo}
                src="/vercel.svg"
                alt="Vercel logomark"
                width={20}
                height={20}
              />
              Cycle color
            </a>
          </div>
          <div className={styles.ctas}>
            <CycleButton colors={colors} />
          </div>
        </main>
      </div>
    </>
  );
}

export default Home;
